### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#11]
![capture 1](https://cloud.githubusercontent.com/assets/17867992/17454633/e216812c-5bcf-11e6-9d6c-ccd65bd84679.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/17867992/17454634/e5361336-5bcf-11e6-8bf2-6ee277e64692.PNG)

**Comment by abishek** [comment]
I am able to login :(

Abishek

**Comment by abishek** [comment]
This looks like a mysql issue on the python anywhere site. I need to check with the support team. But once we are ready to go production, we may try to move to AWS or something.
