### ISSUE TITLE
missing Order Details

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#13]
![capture 1](https://cloud.githubusercontent.com/assets/17867992/17642651/98600f88-6180-11e6-8859-c7be4e3dd2ef.PNG)

**Comment by abishek** [comment]
Good find. I thought I fixed this. Due to some changes in the content send from front end, I sometimes don’t get the correct orderid into my view and end up inserting incorrect ID. Will fix this and update live sight tonight :)

Abishek

**Comment by abishek** [comment]
Fixed.
