### ISSUE TITLE
pincode is not working

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#4]
![capture](https://cloud.githubusercontent.com/assets/17867992/14063635/1864ccf0-f40d-11e5-8df0-d71414eb375e.JPG)

**Comment by abishek** [comment]
looks you have added an empty hawker without any pincode or other details. Currently, the admin is not meant to be robust because only you are going to use it. if we break the data integrity from admin, we cannot expect the app to work!

**Comment by rvrphoto** [comment]
![capture](https://cloud.githubusercontent.com/assets/17867992/14224362/129d342a-f8cb-11e5-88b1-9dbb69c6f891.JPG)
