### ISSUE TITLE
pincode is not working

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#5]
![capture](https://cloud.githubusercontent.com/assets/17867992/14224372/88870c1a-f8cb-11e5-8759-6a0e79a5eefe.JPG)

**Comment by abishek** [comment]
boss, does this pincode exist?

**Comment by rvrphoto** [comment]
got the similar error for valid postal code
![haw](https://cloud.githubusercontent.com/assets/17867992/16416978/fa0dc302-3d76-11e6-9b13-84ef3db14a0b.JPG)

**Comment by abishek** [comment]
This was a database issue. And a view URL issue in the angular code. Should not occur going forward.
