### ISSUE TITLE
Image uploading using browse option 

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#7]
![capture](https://cloud.githubusercontent.com/assets/17867992/14224522/1c107b82-f8d2-11e5-9621-c7c8cb187d68.JPG)

**Comment by rvrphoto** [comment]
cant upload the image
![capture](https://cloud.githubusercontent.com/assets/17867992/16894170/6e155c7a-4b81-11e6-8739-fc246f61cb18.JPG)
![capture](https://cloud.githubusercontent.com/assets/17867992/16894175/8dbee3f2-4b81-11e6-9e2d-2c0b41a036ba.JPG)

**Comment by abishek** [comment]
Fixed in rework.
