### ISSUE TITLE
 Can't login with vndr/vndrP for basic vendor user.

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#8]

**Comment by abishek** [comment]
I am able to login. I just checked.

Abishek

**Comment by rvrphoto** [comment]
able to login today. Thanks

**Comment by rvrphoto** [comment]
not able to update the vendor information. 
![capture](https://cloud.githubusercontent.com/assets/17867992/16538184/87190b60-404e-11e6-9a3a-3bc7b1f056b0.JPG)

**Comment by rvrphoto** [comment]
not able to update the vendor information.
