### ISSUE TITLE
can't add a stall 

### ISSUE THREAD

**Issue by rvrphoto** [abishek/hawkers#9]
![capture](https://cloud.githubusercontent.com/assets/17867992/17274454/91cb9938-5714-11e6-95c4-65e4bd3ad529.PNG)

**Comment by abishek** [comment]
Can pincode start with 0? I treat it as a 6 digit number now, maybe that is why this is failing.

Abishek

**Comment by rvrphoto** [comment]
![capture](https://cloud.githubusercontent.com/assets/17867992/17274464/fdf8dd8c-5714-11e6-9627-9939abea5372.PNG)

**Comment by rvrphoto** [comment]
pincode can start with 0

**Comment by abishek** [comment]
Ok. Then I need to modify the requirement there.

Also contact number is a 8 digit integer, so we cannot have space there. It becomes very involved to support all possible formats in the first revision, that’s why kept it basic.

Abishek

**Comment by abishek** [comment]
Updated with fix. Re Open if issue still exists.
